allowBuilds:
  '@prisma/engines': true
  '@whiskeysockets/baileys': true
  better-sqlite3: true
  bufferutil: true
  es5-ext: false
  esbuild: true
  ffmpeg-static: true
  prisma: true
  protobufjs: true
  utf-8-validate: true
minimumReleaseAgeExclude:
  - '@whiskeysockets/baileys@7.0.0-rc14'
