allowBuilds:
  '@prisma/engines': true
  '@whiskeysockets/baileys': true
  better-sqlite3: true
  esbuild: true
  ffmpeg-static: true
  prisma: true
  protobufjs: true
minimumReleaseAgeExclude:
  - '@whiskeysockets/baileys@7.0.0-rc14'
