import { Groq } from 'groq-sdk';
import { WASocket, WAMessage } from '@whiskeysockets/baileys';
import { writeLog } from '#/logger.js';
import dotenv from 'dotenv';
import { isGroupWhitelisted } from '#/db.js';
import { addMessageToHistory, getConversationContext } from '#/utils/aiHistory.js';

dotenv.config();

let isGlobalOfflineAiEnabled = false;

// Buffer to hold incoming messages while waiting for the 3-second delay
const messageBuffer = new Map<string, string[]>();

// Keeps track of JIDs that are currently being processed
const processingJids = new Set<string>();

export function toggleOfflineAi(): boolean {
    isGlobalOfflineAiEnabled = !isGlobalOfflineAiEnabled;
    return isGlobalOfflineAiEnabled;
}

export function isOfflineAiEnabled(): boolean {
    return isGlobalOfflineAiEnabled;
}

let groqClient: Groq | null = null;
function getGroqClient(): Groq {
    if (!groqClient) {
        groqClient = new Groq({ apiKey: process.env.GROQ_API_KEY });
    }
    return groqClient;
}

export async function handleOfflineAiResponder(sock: WASocket, msg: WAMessage, jid: string, text: string): Promise<boolean> {
    if (!isGlobalOfflineAiEnabled) return false;

    // Do not respond to commands
    if (text.trim().startsWith('.')) return false;
    
    // Ignore empty messages
    if (!text.trim()) return false;

    // If it's a group, only respond if whitelisted
    if (jid.endsWith('@g.us')) {
        const whitelisted = await isGroupWhitelisted(jid);
        if (!whitelisted) return false;
    }

    // Add message to buffer
    const currentBuffer = messageBuffer.get(jid) || [];
    currentBuffer.push(text.trim());
    messageBuffer.set(jid, currentBuffer);

    // Anti-spam system: check if already processing a message from this JID
    if (processingJids.has(jid)) {
        console.log(`[Offline AI] Queued additional message bubble for ${jid}`);
        return true; 
    }

    processingJids.add(jid);

    try {
        // Delay 3 seconds with "composing" status
        await sock.sendPresenceUpdate('composing', jid);
        await new Promise(resolve => setTimeout(resolve, 3000));
        
        // Re-update presence as it might expire or we just want to ensure it's still composing
        await sock.sendPresenceUpdate('composing', jid);
        
        // After 3 seconds, gather all buffered messages and clear buffer
        const finalMessages = messageBuffer.get(jid) || [];
        messageBuffer.delete(jid);
        const combinedText = finalMessages.join('\n\n');
        
        if (!combinedText) return false;

        // Add the new combined user message to history
        addMessageToHistory(jid, 'user', combinedText);

        const systemPrompt = `You are a helpful AI assistant replying on behalf of the user who is currently offline.
Engage in casual conversation with the contacts while they wait for the user to come back online.
Keep your responses friendly, casual, and natural. Do not mention that you are an AI unless explicitly asked, act naturally as a stand-in.
CRITICAL INSTRUCTION: Always reply in the exact same language that the contact is using (e.g., if they speak Indonesian, reply in Indonesian; if they speak Spanish, reply in Spanish).
Important: Reply natively. Do not use XML tags for function calls. Return ONLY the text you want to send.`;

        const groq = getGroqClient();
        
        // Retrieve the conversation context (includes summary and recent messages)
        const chatContext = await getConversationContext(jid, groq);

        const response = await groq.chat.completions.create({
            model: 'openai/gpt-oss-20b',
            messages: [
                { role: 'system', content: systemPrompt },
                ...chatContext
            ],
            temperature: 0.7
        });
        
        const aiText = response.choices[0]?.message?.content?.trim();
        if (aiText) {
            // Save AI response to history
            addMessageToHistory(jid, 'assistant', aiText);

            const finalReply = `${aiText}\n\n> Message generated by AI may contain errors; please double-check`;
            await sock.sendMessage(jid, { text: finalReply }, { quoted: msg });
            writeLog('INFO', 'Offline AI responded', { jid, responseLength: finalReply.length });
        }
        return true;
    } catch (err: any) {
        console.error('[Offline AI Groq Error]', err);
        writeLog('ERROR', 'Offline AI Groq completion failed', { error: err.message });
        return false;
    } finally {
        processingJids.delete(jid);
    }
}
